### PR TITLE
Add handling of the removal of std::unary_function in C++17

### PR DESCRIPTION
**Pull request by srherbener**
## Description

The C++17 standard specifies that std::unary_function is to be removed. Boost has `#define` directives to handle this, but this requires defining the cxxflag `BOOST_NO_CXX98_FUNCTION_BASE` on the build (b2) command line. This PR adds in a check for C++17 or newer and adds in the define mentioned above.

This was discovered when trying to build on the Mac using the new apple-clang@15.0.0 version. Apparently Apple did not remove std::unary_function until version 15.0.0 was released.

## Issue(s) addressed

None

## Dependencies

List the other PRs that this PR is dependent on:
None

## Impact

Expected impact on downstream repositories:
None

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (N/A)
- [x] I have run the unit tests before creating the PR (tested manually on my Mac)

### CODE REVIEW

**Comment by climbfuji** [comment]
Also here it would be good to cherry-pick the updates for boost from spack develop and then applying the changes for all versions.

**Comment by srherbener** [comment]
After fixing the syntax error, I re-tested on my Mac and boost built successfully.

**Comment by srherbener** [comment]
After fixing the coding style error, I re-tested on my Mac and boost built successfully.

**Review by climbfuji — APPROVED** [review]
CI tests passed for the associated spack-stack PR.

**Pull request merged**
