### PR TITLE
Change variant fpic to pic for fms

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR changes `fpic` to `pic` for fms to make it consistent with everything else.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
This will require changes in spack-stack, I think ...

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Ok if we merge this after creating release branches?

**Comment by mathomp4** [comment]
Also @AlexanderRichert-NOAA have you made a similar PR to mainline spack? Or would you like me to?

**Comment by AlexanderRichert-NOAA** [comment]
Yep this isn't urgent, just part of a batch of changes I'll want in the near future. @mathomp4 if you're making changes to fms in main spack then go ahead, otherwise I'll take care of it.

**Comment by AlexanderRichert-NOAA** [comment]
Going to do this as part of a larger batch of changes...

**Pull request closed without merging**
