### PR TITLE
NCEPLIBS oneAPI support

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR updates the recipes for sigio, sfcio, landsfcutil, and gfsio to add the versions that support oneAPI (which in practice is just a CMake update to apply the Intel flags to the 'IntelLLVM' compiler case).

Addresses https://github.com/JCSDA/spack-stack/issues/1279

### CODE REVIEW

**Comment by climbfuji** [comment]
Note, I will review and test this once 1.8.0 is out the door.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA I am sorry I totally overlooked this PR! Can you look at the merge conflict, please, and I will review and merge promptly. Thanks!

**Comment by ulmononian** [comment]
@rickgrubin-noaa fyi...

**Comment by climbfuji** [comment]
looks like this is a no-PR after the update of spack-stack-dev from spack develop?

**Comment by AlexanderRichert-NOAA** [comment]
Yep :)

**Pull request closed without merging**
