### PR TITLE
Merge spack v0.18

### PR DESCRIPTION
**Pull request by kgerheiser**
Working on https://github.com/NOAA-EMC/spack-stack/issues/161

Fixed all conflicts, going to test now.

### CODE REVIEW

**Comment by climbfuji** [comment]
> Working on [NOAA-EMC/spack-stack#161](https://github.com/NOAA-EMC/spack-stack/issues/161)
> 
> Fixed all conflicts, going to test now.

I started looking into this 30mins ago. There were many conflicts, and for some we need to be very careful to keep what's needed by us. We'll need to test this version on all platforms, not just the CI tests and a local macOS :-(

**Comment by kgerheiser** [comment]
Agreed. I think I was pretty careful with merging.

**Comment by climbfuji** [comment]
I found a few differences between my branch and yours. I am checking those now, will send you a PR for consideration.

**Comment by climbfuji** [comment]
@kgerheiser I have a bugfix/recommendations branch for you, but I can't issue a PR for your fork for whatever reason:

Can you look at https://github.com/climbfuji/spack/tree/feature/spack_v0p18p0_dom or pull that branch in, please? I have only one question in netcdf-fortran, for all others I am pretty sure I got it right (either I pulled your version over into mine or vice versa).

Thanks!

**Comment by kgerheiser** [comment]
I merged in your branch. I re-did the change in cray-mpich with the compilers, and the change I made in OpenMPI, but was able to take everything else from you.

**Comment by climbfuji** [comment]
> I merged in your branch. I re-did the change in cray-mpich with the compilers, and the change I made in OpenMPI, but was able to take everything else from you.

Great, thanks! Curious what this new version does to systems like gaea.

**Comment by kgerheiser** [comment]
>  Curious what this new version does to systems like gaea.

Do you mean what I said about cray-mpich? That's a change I made. It's a bug where regular MPI wrappers like `mpicc` are assumed to be present, but aren't. https://github.com/spack/spack/issues/29459

Or just in general?

**Comment by kgerheiser** [comment]
A big improvement should be usable concretization errors.

**Comment by climbfuji** [comment]
> > Curious what this new version does to systems like gaea.
> 
> Do you mean what I said about cray-mpich? That's a change I made. It's a bug where regular MPI wrappers like `mpicc` are assumed to be present, but aren't. [spack#29459](https://github.com/spack/spack/issues/29459)

Ahh no, I meant in general from the release notes. Sorry for not being clear.

Once the CI testing and your local testing are all looking good, we should test the various HPCs ...

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
