### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by kgerheiser**
Broke something in my previous PR.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
Some CI tests fail, e.g. the linux tests/unittests:
```
14s
[1](https://github.com/NOAA-EMC/spack/runs/7307521545?check_suite_focus=true#step:8:1)
Run . share/spack/setup-env.sh
[10](https://github.com/NOAA-EMC/spack/runs/7307521545?check_suite_focus=true#step:8:11)
==> "spack-install" is now untrusted and will not be used for bootstrapping
[11](https://github.com/NOAA-EMC/spack/runs/7307521545?check_suite_focus=true#step:8:12)
==> Error: Package 'py-pyhdf' not found.
[12](https://github.com/NOAA-EMC/spack/runs/7307521545?check_suite_focus=true#step:8:13)
==> Bootstrapping clingo from pre-built binaries
[13](https://github.com/NOAA-EMC/spack/runs/7307521545?check_suite_focus=true#step:8:14)
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.2/build_cache/linux-rhel5-x86_64-gcc-9.3.0-clingo-bootstrap-spack-gypv5loj2ml73duq6sr76yg5rj25te2m.spec.json
[14](https://github.com/NOAA-EMC/spack/runs/7307521545?check_suite_focus=true#step:8:15)
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.2/build_cache/linux-rhel5-x86_64/gcc-9.3.0/clingo-bootstrap-spack/linux-rhel5-x86_64-gcc-9.3.0-clingo-bootstrap-spack-gypv5loj2ml73duq6sr76yg5rj25te2m.spack
[15](https://github.com/NOAA-EMC/spack/runs/7307521545?check_suite_focus=true#step:8:16)
==> Installing "clingo-bootstrap@spack%gcc@9.3.0~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-rhel5-x86_64" from a buildcache
[16](https://github.com/NOAA-EMC/spack/runs/7307521545?check_suite_focus=true#step:8:17)
Error: Process completed with exit code 1.
```

**Comment by kgerheiser** [comment]
I see that, but I'm not sure what it is. I just tried running `spack install py-pyhdf` with no issue. And where is `py-pyhdf` coming from in the Linux tests?

**Comment by climbfuji** [comment]
> I see that, but I'm not sure what it is. I just tried running `spack install py-pyhdf` with no issue. And where is `py-pyhdf` coming from in the Linux tests?

I won't have time to look into this today, I fear.

**Comment by climbfuji** [comment]
it's okay to merge because this PR is independent and a needed bug fix.

**Comment by kgerheiser** [comment]
I think it's something like `py-pyhdf` is in the `builtin` repo of jcsda-emc and not in develop

**Pull request merged**
