### PR TITLE
Add shared variant to Bufr

### PR DESCRIPTION
**Pull request by kgerheiser**
And properly check for the right library type when it can be +shared/~shared.

Using shared libraries avoids issues when linking to MET because of issues with common symbols on macOS.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Should we add an fPIC variant since we are already working on the package?

**Comment by kgerheiser** [comment]
I could do that, but building a shared library implies position independent code so that a `pic` variant would only be useful when building static. What do you think?

**Comment by climbfuji** [comment]
> I could do that, but building a shared library implies position independent code so that a `pic` variant would only be useful when building static. What do you think?

Sure, I was wondering if we should add the fPIC for the _existing_ static build, similar to what you did last week for sp etc.

**Comment by kgerheiser** [comment]
I would say if you need `pic` then you should use the shared library variant instead (which is the default).

**Comment by climbfuji** [comment]
I think that's a fair statement.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
