### PR TITLE
Add esmf@8.8.0b06

### PR DESCRIPTION
**Pull request by climbfuji**
Add esmf@8.8.0b06. As usual, these beta snapshots are not intended for the upstream spack develop.

Contains a tiny bug fix so that the `chmod_scripts` patch is really only applied for `@:7.0` (will create PR for this for spack develop).

I also removed old, unused snapshots from the package.

Testing in spack-stack: https://github.com/JCSDA/spack-stack/pull/1385

### CODE REVIEW

**Review by theurich — APPROVED** [review]
Valid sha256.

**Review by theurich — CHANGES_REQUESTED** [review]
I am second guessing my previous PR approval... because I am running into problems using the spack-stack install on Nautilus with the `gerhard/hinterp-conserve` branch. 

I see that we typically use the **commit** hash for beta tags, and sha256 only for official release tags. I would not think that this matters, since I validated the sha256 with `spack checksum esmf 8.8.0b06`. But maybe it is safer to use the commit hash for beta tags??? If so, the correct commit hash for `v8.8.0b06` is `aed3278586544bb7687bb03b5c9b65dff67c18a8`.

**Comment by climbfuji** [comment]
Oh no. I can change that, but then I need to reinstall ESMF.

**Comment by theurich** [comment]
> Oh no. I can change that, but then I need to reinstall ESMF.

Let me try to understand this better before you do the extra work.

**Comment by climbfuji** [comment]
> > Oh no. I can change that, but then I need to reinstall ESMF.
> 
> Let me try to understand this better before you do the extra work.

That would be great. I made the sha to commit change, but I worry that there are new/different build options than what we've used in the past.

**Review by theurich — COMMENTED** [review]
I validated that what you get with 
```
version("8.8.0b06", sha256="760c9c628e6a4b6560434f7f7285c74eef7c9262fa49c8b87ca9bbb638b62518")
```
is the same as with
```
version("8.8.0b06", commit="aed3278586544bb7687bb03b5c9b65dff67c18a8")
```
So that is not the difference/problem.

**Review by theurich — CHANGES_REQUESTED** [review]
There is a duplicate ESMF `8.6.1` in the list of versions. I think the one on line 37 of `var/spack/repos/builtin/packages/esmf/package.py` should be deleted. 
Also not sure if  `8.6.1b04` is still relevant for anyone using spack-stack? Less sure about the `8.7.0b*`.

**Comment by climbfuji** [comment]
I fixed the duplicates and removed the old, unused snapshots

**Review by theurich — APPROVED** [review]
Thank you! Looks good to me now.

**Pull request merged**
