### PR TITLE
Update udunits, nco, zstd, glib, libxpm

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
## Description

This PR adds a pic variant for udunits, correct the find_libraries() call in udunits, adds static netcdf-c support to nco, and pic variant for zstd. No changes to default variants etc. w.r.t. spack-stack.

## Issue(s) addressed

--

## Dependencies

--

## Impact

--

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Is this already in spack develop?

**Comment by AlexanderRichert-NOAA** [comment]
As with #348, I'm putting it in jcsda spack first so it's available for NCO to work with through spack-stack. That said, these changes are consistent with how we've done things for other packages so I don't expect any "controversy" as far as pushing them into main spack.

**Review by climbfuji — COMMENTED** [review]
Looks ok to me, but would be nice if we could run the CI tests for this (consider merging the simpler zstd PR first so that that change gets tested as part of this PR, too?

**Comment by AlexanderRichert-NOAA** [comment]
Sure, will do

**Comment by climbfuji** [comment]
> Sure, will do

Thanks very much!

**Comment by AlexanderRichert-NOAA** [comment]
messed up this branch- I'll start over and do a PR with the whole batch of changes

**Comment by climbfuji** [comment]
> messed up this branch- I'll start over and do a PR with the whole batch of changes

Sorry, this was not my intention!

**Pull request closed without merging**
