### PR TITLE
sfcio: add v1.4.2 (#46146)

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
Cherry-picking 8cac746 from main Spack. Needed for UFS_UTILS, so no need to change default yet.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
I think we need to bump the default because of the conflicts you are adding? We have oneapi@ compilers that work fine with the current versions of nceplibs (sfcio 1.4.1 etc) as long as ifort is used instead of ifx; and we need to use oneapi@ to distinguish them from the intel@ compilers that use icc, icpc.

**Comment by AlexanderRichert-NOAA** [comment]
Sure, I'll make a spack-stack PR

**Comment by climbfuji** [comment]
> Sure, I'll make a spack-stack PR

Can you also include yesterday's update to sigio (?) please?

**Comment by AlexanderRichert-NOAA** [comment]
See https://github.com/JCSDA/spack-stack/pull/1358

**Pull request merged**
