### PR TITLE
Add awscli-v2 and its dependency py-awscrt

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Add new package awscli-v2 and its dependency py-awscrt. The corresponding spack PR, including a discussion on whether to create a new package or not, with the exact same commits (cherry-picked) is https://github.com/spack/spack/pull/40288. It's been approved and waiting to be merged. (UPDATE: got merged Oct 4).

I tested building `awscli-v2` and successfully ran a few `aws` commands from that installation on my macOS with clang@13.1.6.

This PR can be merged immediately, since the new packages are not used anywhere in our spack-stack recipes.

## Issue(s) addressed

Working towards https://github.com/JCSDA/spack-stack/issues/801

## Dependencies

n/a

## Impact

n/a

## Checklist

- [x] I have performed a self-review of my own code
- [ ] ~~I have made corresponding changes to the documentation~~
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by climbfuji** [comment]
The spack develop PR https://github.com/spack/spack/pull/40288 was merged earlier today

**Review by srherbener — APPROVED** [review]

**Comment by climbfuji** [comment]
I'll go ahead and merge this, this PR does nothing but adding new packages that aren't used anywhere as of now in spack-stack. There will be a follow-up PR that enables this version awscli-v2 in favor of awscli (v1), at which time it will be good to have @ashley314's testing results.

**Comment by ashley314** [comment]
@climbfuji sounds good! I will keep an eye out for that and let you know how it goes. Thanks!

**Comment by ashley314** [comment]
Following up... Testing this version with the `aws s3 sync` command used in the background ingest suite worked well on my mac. @climbfuji I think we are good to go with the follow-up PR, thanks!

**Pull request merged**
