### PR TITLE
Updates required for creating binary (build) caches

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

These updates are required for creating build caches for all packages in an environment by skipping packages with errors instead of aborting, which is what spack does at the moment. I created a corresponding issue and PR in the upstream spack repo: https://github.com/spack/spack/issues/35602 and https://github.com/spack/spack/pull/35601.

Note that the changes differ slightly from this PR due to the updates that went into spack develop in these files. I will take care of resolving the conflicts when we bring these changes down to our fork).

## Testing
Tested successfully on my macOS. See https://github.com/NOAA-EMC/spack-stack/pull/484 for the corresponding spack-stack PR.

### CODE REVIEW

**Comment by climbfuji** [comment]
The CI test failure doesn't look like it is related to this PR (https://github.com/NOAA-EMC/spack/actions/runs/4263344812/jobs/7419969492):
```
FAILED lib/spack/spack/test/llnl/util/lock.py::test_write_lock_timeout_on_write[/run/user/1001] - assert False
```
I think this PR is ready to go!

**Comment by climbfuji** [comment]
> The CI test failure doesn't look like it is related to this PR (https://github.com/NOAA-EMC/spack/actions/runs/4263344812/jobs/7419969492):
> 
> ```
> FAILED lib/spack/spack/test/llnl/util/lock.py::test_write_lock_timeout_on_write[/run/user/1001] - assert False
> ```
> 
> I think this PR is ready to go!

Ah, and rerunning it fixed it :-)

**Review by srherbener — APPROVED** [review]
Didn't test but changes look good to me.

**Review by ulmononian — APPROVED** [review]
will be very nice to have this improved build cache feature. approved.

**Pull request merged**
