### PR TITLE
Merge spack/develop as of 2024/01/26 into jcsda_emc_spack_stack

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Pull in spack develop as of 2024/01/26 - needed for JEDI+GEOS development, and generally good to stay up to date. Every single package has changed because of the copyright date change (2013-2023 --> 2013-2024).

I would like the reviewers to specifically look at the following packages for which I had to resolve merge conflicts that weren't entirely trivial, or for which I needed to add more code (`nco` and `openmpi`).
```
var/spack/repos/builtin/packages/cmake/package.py
var/spack/repos/builtin/packages/ecmwf-atlas/package.py
var/spack/repos/builtin/packages/libjpeg-turbo/package.py
var/spack/repos/builtin/packages/mapl/package.py
var/spack/repos/builtin/packages/met/package.py
var/spack/repos/builtin/packages/mysql/package.py
var/spack/repos/builtin/packages/nco/package.py
var/spack/repos/builtin/packages/openmpi/package.py
```

## Issues

This is all part of compiling JEDI+GEOS with spack-stack (i.e. not using Baselibs) on more than just Discover: https://github.com/JCSDA-internal/AOP23/issues/33

## Testing

- Usual CI tests, see below
- See https://github.com/JCSDA/spack-stack/pull/977 for spack-stack testing

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
The only thing that stands out to me is MySQL-- Let's restore the `+download_boost` functionality since we're still using it in common/packages.yaml, unless we have a different solution there.

**Review by RatkoVasic-NOAA — APPROVED** [review]
I checked mentioned package.py's and differences with old ones. Looks good to me.

**Comment by climbfuji** [comment]
> The only thing that stands out to me is MySQL-- Let's restore the `+download_boost` functionality since we're still using it in common/packages.yaml, unless we have a different solution there.

Do we need this functionality? On all the HPCs as well as on all the user platforms we rely on mysql being provided as an external package? I'd rather remove that option unless you remind me of why we need it ;-)

**Comment by AlexanderRichert-NOAA** [comment]
https://github.com/JCSDA/spack-stack/issues/705

**Comment by climbfuji** [comment]
> [JCSDA/spack-stack#705](https://github.com/JCSDA/spack-stack/issues/705)

That would have been my guess but I don't recall what the `download_boost` option gives us? We need to build boost in spack anyway for other reasons (not just ecflow or mysql, but JEDI itself requires it).

**Comment by AlexanderRichert-NOAA** [comment]
It downloads and uses its own internal boost libraries, so it doesn't impose version constraints on the Spack-installed boost.

**Comment by climbfuji** [comment]
> It downloads and uses its own internal boost libraries, so it doesn't impose version constraints on the Spack-installed boost.

Ok, so because of the version constraints for mysql. Let me try to put it back in. CI won't test it though.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA I have another suggestion. What about if we take `mysql` out of the default dependencies and only enable it (as external package) for macOS users who wish to run JEDI-Skylab experiments on their laptops, and on 2 particular systems managed by JCSDA (on AWS)? There is only one particular use case for a local mysql server, and that is running JEDI-Skylab in "localhost" mode. This only happens on macOS laptops at JCSDA, on the JEDI Singlenode AMI for AWS, and on AWS ParallelCluster - all HPCs, all non-JCSDA user installations, all other cloud systems can be installed w/o mysql.

**Comment by AlexanderRichert-NOAA** [comment]
Take it off the HPC systems? Yes that sounds lovely :)

**Review by srherbener — APPROVED** [review]
The changes in the listed package.py scripts seem okay. I noticed that the openmpi patch for apple-clang two level namespace has this addition:
```
+    @when("@5.0.0:5.0.1")
+    def autoreconf(self, spec, prefix):
+        perl = which("perl")
+        perl("autogen.pl", "--force")
+        if "+two_level_namespace" in spec and spec.satisfies("platform=darwin"):
+            print("Re-applying configure patch for two_level_namespace on MacOS after autoreconf")
+            filter_file(r"-flat_namespace", "-commons,use_dylibs", "configure")
+
```
which looks like re-applying the patch for two level namespace when autoreconf is run. This seem like a good thing for us to pick up. Just wanted to point that out.

**Comment by climbfuji** [comment]
> Take it off the HPC systems? Yes that sounds lovely :)

Ok, then I'll do that. I leave the PR as is, and file a bug to redo the mysql dependency in the way I described above. Is that ok with you?

**Comment by AlexanderRichert-NOAA** [comment]
Yep works for me! Thanks

**Comment by climbfuji** [comment]
> The changes in the listed package.py scripts seem okay. I noticed that the openmpi patch for apple-clang two level namespace has this addition:
> 
> ```
> +    @when("@5.0.0:5.0.1")
> +    def autoreconf(self, spec, prefix):
> +        perl = which("perl")
> +        perl("autogen.pl", "--force")
> +        if "+two_level_namespace" in spec and spec.satisfies("platform=darwin"):
> +            print("Re-applying configure patch for two_level_namespace on MacOS after autoreconf")
> +            filter_file(r"-flat_namespace", "-commons,use_dylibs", "configure")
> +
> ```
> 
> which looks like re-applying the patch for two level namespace when autoreconf is run. This seem like a good thing for us to pick up. Just wanted to point that out.

Yes, that is needed. As you can see from the code snippet, for openmpi@5: it currently enforces an `autoreconf`, which overwrites the `configure` file you patched earlier. I kept the original logic above in place (always patch the default `configure`) in case someone removes these forced autoreconf in the future.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA See https://github.com/JCSDA/spack-stack/issues/990 - if satisfied, please approve. Thanks!

**Review by ulmononian — APPROVED** [review]

**Review by AlexanderRichert-NOAA — APPROVED** [review]
Built unified-dev and ufs-weather-model-static on Gaea, everything checks out. Checked recipe diffs and everything looks reasonable.

**Comment by climbfuji** [comment]
Thanks @AlexanderRichert-NOAA and all other reviewers!

**Pull request merged**
