### PR TITLE
containerize: fix concretization -> concretizer (#31594)

### PR DESCRIPTION
**Pull request by kgerheiser**
Pull this fix into our branch from Spack develop. The container needed to be updated with the new `concretizer` config.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
Great! I saw these warnings, happy to see them go.

**Comment by climbfuji** [comment]
@mer-a-o FYI

**Comment by kgerheiser** [comment]
The test doesn't like that `crtm` (within `builtin`) has a dependency on `crtm-fix` (`jcsda-emc`) and similarly for fms and jedi-cmake

**Comment by climbfuji** [comment]
> The test doesn't like that `crtm` (within `builtin`) has a dependency on `crtm-fix` (`jcsda-emc`) and similarly for fms and jedi-cmake

What's your suggestion on how to fix that problem?

**Comment by kgerheiser** [comment]
It makes sense that packages in builtin shouldn't have a dependency on an outside repo. I guess moving jedi-cmake and crtm-fix into `builtin` is the easiest solution. Else ignore it or keep modified packages within `jscda-emc` and the originals in `builtin` and you end up with a duplicate.

**Comment by kgerheiser** [comment]
Longer term, I will add crtm-fix into Spack in some form, but I'm thinking it should be done with git-lfs along with crtm itself. I believe I had some issue with that and it made sense to download it as a tarball for versioning.

Related to this discussion https://github.com/NOAA-EMC/spack/issues/131

And isn't jedi-cmake a temporary fix for FMS?

**Comment by kgerheiser** [comment]
Going to merge, this commit has already been accepted to the main repo. The full set of tests are running since a core Spack file was modified.

**Pull request merged**
