### PR TITLE
Adding latest version of openblas (0.3.24)

### PR DESCRIPTION
**Pull request by srherbener**
## Description

This PR adds in the version statement for the latest openblas version which is 0.3.24. This is needed to enable building with the latest apple-clang@15.0.0 version.

## Issue(s) addressed

None

## Dependencies

List the other PRs that this PR is dependent on:
None

## Impact

Expected impact on downstream repositories:
None

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (N/A)
- [x] I have run the unit tests before creating the PR (tested building on my Mac)

### CODE REVIEW

**Review by climbfuji — CHANGES_REQUESTED** [review]
This version already exists in spack develop. We should pull these updates in (cherry-pick them) to avoid future merge conflicts.

**Comment by srherbener** [comment]
Re-tested on my Mac and openblas built successfully.

**Comment by climbfuji** [comment]
Can you create a spack-stack PR for this? Would be good to test/see how you enforce the update to that version for clang 15 (or update across the board?).

**Comment by climbfuji** [comment]
> Can you create a spack-stack PR for this? Would be good to test/see how you enforce the update to that version for clang 15 (or update across the board?).

Or, if you know for sure that this version is going to be ignored, it's fine too.

**Comment by srherbener** [comment]
> Can you create a spack-stack PR for this? Would be good to test/see how you enforce the update to that version for clang 15 (or update across the board?).

See https://github.com/JCSDA/spack-stack/pull/809. For now, I chose to update the version in the `common/packages.yaml` since it would be easier if all the platforms could upgrade. But, I realize that this isn't necessarily pragmatic and I'm completely open to leaving `common/packages.yaml` as is and configuring specifically for the Mac.

**Review by climbfuji — APPROVED** [review]
CI tests passed.

**Pull request merged**
