### PR TITLE
Simplify spack stack extension

### LINKED ISSUE #195: Simplify `spack stack` extension for first release
The full set of options for the `spack stack` extension is:
```
spack stack [create|setup-meta-modules]

spack stack create [env|container]

# This is way too complicated and confusing!
spack stack create env [--template TEMPLATE] [--specs [SPECS [SPECS ...]]] [--name NAME] [--dir DIR] [--overwrite] [--packages PACKAGES] [--site SITE] [--prefix PREFIX] [--envs-file ENVS_FILE]

# This is not as bad, but still too complicated and confusing!
spack stack create container [--template TEMPLATE] [--specs [SPECS [SPECS ...]]] [--name NAME] [--dir DIR] [--overwrite] [--packages PACKAGES] container
```

Suggestions/questions for `env` and `container`:
1. Get rid of `--specs` - tell user to use template `TEMPLATE` (default `empty`), and when using empty, add specs (can refer to section _Environments_ in the documentation - this section is still missing, but will be completed before the release).2. 

Suggestions/questions for `env`:
2. Get rid of `--envs-file`? if users want to create an environment from a complete envs file, they don't need the overhead of running `spack stack create env`, they can just create a directory and copy the envs file there. It's also something that likely only advanced users want to do, therefore don't need to document? Can add some documentation if we think it is worth it.
3. Why do we need `--prefix` and `--dir`? Should we just always place the enviroment in `envs/name` and let the user overwrite only `prefix`?

Suggestions/questions for `container`:
4. In the help for the command, replace the container option with `container-option` or something like that, because we have `spack stack create container ... container` and that is confusing.
5. Same as for `env`, should we get rid of `--dir`?

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Simplifies the spack stack extension by removing several arguments/options that are not needed. See https://github.com/NOAA-EMC/spack-stack/issues/195 for details.

Fixes https://github.com/NOAA-EMC/spack-stack/issues/195.

This PR must be merged before https://github.com/NOAA-EMC/spack-stack/pull/196 and it requires follow-up documentation changes.

### CODE REVIEW

**Comment by kgerheiser** [comment]
You're on the right track

**Comment by climbfuji** [comment]
Unfortunately the concretize tests are still failing, absolutely silently, no output :-(

**Comment by climbfuji** [comment]
https://github.com/NOAA-EMC/spack-stack/runs/6835335960?check_suite_focus=true

**Comment by kgerheiser** [comment]
`==> Error: Attempted to use external for 'python' which does not satisfy any configured external spec`

**Comment by climbfuji** [comment]
> ==> Error: Attempted to use external for 'python' which does not satisfy any configured external spec

Got that on my system, too, but wondering why there is no output in the CI tests.

**Comment by kgerheiser** [comment]
Using your branch on my machine to build jedi-ufs-all appears to be working

**Comment by climbfuji** [comment]
Weird. Putting steps back in one by one on CI, checking the raw logs.

**Comment by climbfuji** [comment]
@kgerheiser This is ready to merge and will be the last PR for the spack submodule before creating the `jcsda_emc_release_v1` branch and the `spack-stack-1.0.0-rc1` release candidate.

**Review by kgerheiser — APPROVED** [review]

**Pull request merged**
