### PR TITLE
Fix JCSDA-EMC container unit tests

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Need to exclude `README.md` from list of container recipes (it's simply looking for all files in `configs/containers`. Lines 47-48 in `lib/jcsda-emc/spack-stack/tests/test_stack_create.py`.

Also need to "black-format" `lib/jcsda-emc/spack-stack/tests/test_stack_create.py` to make the spack style tests pass (all remaining changes).

This fixes the unit test problem in spack-stack PRs. The style tests now also pass. The remaining CI test errors are due to jedi-cmake not being in the authoritative repo (but in `jcsda-emc`), something we don't have a good solution for.
```
=================================== FAILURES ===================================
_________________________ test_all_dependencies_exist __________________________

    def test_all_dependencies_exist():
        """Make sure no packages have nonexisting dependencies."""
        missing = {}
        pkgs = [pkg for pkg in spack.repo.path.all_package_names()]
        spack.package_base.possible_dependencies(*pkgs, transitive=True, missing=missing)
    
        lines = ["%s: [%s]" % (name, ", ".join(deps)) for name, deps in missing.items()]
>       assert not missing, "These packages have missing dependencies:\n" + ("\n".join(lines))
E       AssertionError: These packages have missing dependencies:
E         fms: [jedi-cmake]
E       assert not {'fms': {'jedi-cmake'}}
```

**Also included:** cherry-picking an update from spack to build a newer version of `curl` with the Intel compiler in the containers (`7.85.0`). Older versions of `curl` fail to build with Intel.

### CODE REVIEW

**Review by srherbener — APPROVED** [review]
If I understand correctly, the test failures are all understood and we don't have a good solution to get them to pass. If so, how are we going to handle the test failures? Will the tests at the spack-stack level show that everything is okay at this (spack) level?

**Comment by srherbener** [comment]
Sorry, I accidentally typed something which caused my review to be "approve" where I meant it to be "comment". So I reset my review.

**Comment by climbfuji** [comment]
> If I understand correctly, the test failures are all understood and we don't have a good solution to get them to pass. If so, how are we going to handle the test failures? Will the tests at the spack-stack level show that everything is okay at this (spack) level?

Yes, this is annoying and concerning. There is no point in running tests if we can't make them pass. I was thinking that I would try to pull in the latest spack updates from the authoritative repo after the spack-stack-1.1.0 release and make all tests pass. I am hesitant to do this before the release, though.

**Comment by climbfuji** [comment]
@mer-a-o @srherbener I think we need to merge this first before we can consider fixing the other tests. I've verified that the container unit test fix works, and I also verified that the new curl version installs cleanly on Orion w/ Intel and in the Intel container. Merging this PR will unblock several other PRs and other work.

**Review by srherbener — APPROVED** [review]
Thanks for the explanation @climbfuji. I'm good with merging this despite the test failures, and dealing with the test failures after spack-stack-1.1.0 release.

**Pull request merged**
