### PR TITLE
Bug fix for py-shapely@1.8.x with external miniconda in spack

### PR DESCRIPTION
**Pull request by climbfuji**
Patch for in `var/spack/repos/builtin/packages/py-shapely/package.py`: if external miniconda is used, don't look for `libgeos_c.so` in the miniconda path, use spack package instead. 

This is only an issue in 1.8.x (and possibly earlier, but we don't use those). Versions 2.x use an entirely different logic to import geos properly.

For testing, see: https://github.com/NOAA-EMC/spack-stack/pull/300

### CODE REVIEW

**Comment by kgerheiser** [comment]
Can we just use a newer 2.x version?

**Comment by climbfuji** [comment]
EDIT: versions 2.x don’t work with the EWOK plotting scripts (we need to use 1.8.0).

**Review by srherbener — APPROVED** [review]
I think the patch looks good. Thanks for fixing this!

**Comment by climbfuji** [comment]
CI tests on Github all completed, my mac is still running but looking ok for the shapely stuff:
```
==> Applied patch /Users/heinzell/work/spack-stack/spack-stack-self-hosted-runner-macos-local/actions-runner/_work/spack-stack/spack-stack/spack/var/spack/repos/builtin/packages/py-shapely/shapely-1.8.0-geos.py.patch
[2409](https://github.com/NOAA-EMC/spack-stack/runs/7680047197?check_suite_focus=true#step:3:2409)
==> Ran patch() for py-shapely
[2410](https://github.com/NOAA-EMC/spack-stack/runs/7680047197?check_suite_focus=true#step:3:2410)
==> py-shapely: Executing phase: 'install'
[2411](https://github.com/NOAA-EMC/spack-stack/runs/7680047197?check_suite_focus=true#step:3:2411)
==> py-shapely: Successfully installed py-shapely-1.8.0-u636ipmqw5gzkxkxu3edpqejhezectyv
```

**Pull request merged**
