### PR TITLE
mepo: new package (spack#44879)

### PR DESCRIPTION
**Pull request by mathomp4**
Supersedes #447 

This PR brings in `mepo` and `py-pyyaml` from spack mainline develop.

### CODE REVIEW

**Comment by mathomp4** [comment]
Huh. I have never seen the "Partially verified" badge.

**Review by climbfuji — APPROVED** [review]
Looks good to me. I think it's part of the unified environment, let's see what CI says ...

**Comment by climbfuji** [comment]
> Looks good to me. I think it's part of the unified environment, let's see what CI says ...

We'll also need a submodule pointer update to test this in the unified environment - I can do that real quick

**Comment by climbfuji** [comment]
spack-stack PR: https://github.com/JCSDA/spack-stack/pull/1179

**Comment by climbfuji** [comment]
CI tests passed for spack-stack PR - will merge this now

**Pull request merged**
