### PR TITLE
Add package gsibec (aka gsibclim)

### LINKED ISSUE #280: Add new package gsibclim
**Please describe the package or library you would like to add to spack-stack.**

NASA has created a new package https://github.com/GEOS-ESM/gsibclim - it's still in relatively early development, but needed soon for JEDI (dependency for SABER). We need to start creating the package in spack-stack and testing it.

**What applications will be using this package or library?**
NASA - JEDI

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
Not that I am aware of.

**Additional context**
@[danholdaway](https://github.com/danholdaway) Can you please provide a bit more information on what this package is? I see some GSI stuff in there (as the name suggests).

**Will This Package be Needed in a NOAA Operational Application?**
Certainly not immediately. I don't know enough about it and how it is integrated in SABER. We will need to revisit the WCOSS System Software Requirements, if necessary, when we know more and when the software is matured.

**WCOSS System Software Request Checklist**
Not applicable now.

### PR DESCRIPTION
**Pull request by climbfuji**
Fixes https://github.com/NOAA-EMC/spack-stack/issues/280

For this version, I decided to turn off Intel MKL by default and use the spack `lapack` provider (as we are doing it for all other packages, e.g. ECMFW's `atlas`).

This packages builds cleanly on my macOS with `apple-clang` and `openmpi`. spack CI tests all passed.

### CODE REVIEW

**Comment by danholdaway** [comment]
@climbfuji I'm not sure what the license should be. Do we know if the GSI has a license? I presume it would be the same.

**Comment by climbfuji** [comment]
> @climbfuji I'm not sure what the license should be. Do we know if the GSI has a license? I presume it would be the same.

https://github.com/noaa-emc/gsi doesn't have a license :-( We can also just remove the boilerplate spack license for now and ask the GSI folks

**Comment by climbfuji** [comment]
> @climbfuji I'm not sure what the license should be. Do we know if the GSI has a license? I presume it would be the same.

https://github.com/noaa-emc/gsi doesn't have a license :-( We can also just remove the boilerplate spack license for now and ask the GSI folks: https://github.com/NOAA-EMC/GSI/issues/476

**Comment by climbfuji** [comment]
@danholdaway @mathomp4 If I remove the boilerplate license and leave it without one for now, would that be ok? I'd like to get those PRs merged before the weekend so that `gsibec` will be included in the next spack-stack release. Thanks ...

**Comment by danholdaway** [comment]
> @danholdaway @mathomp4 If I remove the boilerplate license and leave it without one for now, would that be ok? I'd like to get those PRs merged before the weekend so that `gsibec` will be included in the next spack-stack release. Thanks ...

Fine with me

**Comment by climbfuji** [comment]
> > @danholdaway @mathomp4 If I remove the boilerplate license and leave it without one for now, would that be ok? I'd like to get those PRs merged before the weekend so that `gsibec` will be included in the next spack-stack release. Thanks ...
> 
> Fine with me

Done ... please approve if you can (if not, please state that the package is now ok to merge). Thanks!

**Comment by climbfuji** [comment]
> > > @danholdaway @mathomp4 If I remove the boilerplate license and leave it without one for now, would that be ok? I'd like to get those PRs merged before the weekend so that `gsibec` will be included in the next spack-stack release. Thanks ...
> > 
> > 
> > Fine with me
> 
> Done ... please approve if you can (if not, please state that the package is now ok to merge). Thanks!

Ok, looks like spack expects the package file to carry it's own license. Need to revert. The actual `gsibec` license should go into the `gsibec` repository.
```
==> Error: 1 improperly licensed files
  files with wrong SPDX-License-Identifier:   0
  files with old license header:              0
  files not containing expected license:      1
```

**Comment by mathomp4** [comment]
> @climbfuji I'm not sure what the license should be. Do we know if the GSI has a license? I presume it would be the same.

Note that for GEOS packages I just usually move over the GEOS License which is Apache. And that is [technically in gsibec](https://github.com/GEOS-ESM/GSIbec/blob/develop/LICENSE). That said, I am not at the level of @tclune in re licenses and GEOS, etc. I try my best, but...

ETA: We also have a [`COPYRIGHT` file as well](https://github.com/GEOS-ESM/GSIbec/blob/develop/COPYRIGHT).

**Comment by climbfuji** [comment]
> > @climbfuji I'm not sure what the license should be. Do we know if the GSI has a license? I presume it would be the same.
> 
> Note that for GEOS packages I just usually move over the GEOS License which is Apache. And that is [technically in gsibec](https://github.com/GEOS-ESM/GSIbec/blob/develop/LICENSE). That said, I am not at the level of @tclune in re licenses and GEOS, etc. I try my best, but...
> 
> ETA: We also have a [`COPYRIGHT` file as well](https://github.com/GEOS-ESM/GSIbec/blob/develop/COPYRIGHT).

Ok, thanks for letting me know. Means we are fine on the `gsibec` side.

**Review by danholdaway — APPROVED** [review]

**Pull request merged**
