### PR TITLE
Update release/1.3.1 (starting from release/1.3.0)

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Add many new versions of packages: crtm, ecbuild, eckit, fckit, ecmwf-atlas, gsibec, odc.

## Testing

Tested together with https://github.com/NOAA-EMC/spack-stack/pull/549

### CODE REVIEW

**Comment by BenjaminTJohnson** [comment]
@climbfuji what's the best way to test this on, say, S4?

**Comment by climbfuji** [comment]
Please see https://spack-stack--549.org.readthedocs.build/en/549/PreConfiguredSites.html#uw-univ-of-wisconsin-s4 and use the instructions in that section for `spack-stack-1.3.1`. Let me know if you need help!

**Review by ulmononian — APPROVED** [review]
5stars.

**Comment by climbfuji** [comment]
@BenjaminTJohnson Were you able to test this on S4?

**Review by shlyaeva — APPROVED** [review]
I've tested on pcluster with gnu. All good for jedi-bundle once we merge https://github.com/JCSDA-internal/saber/pull/514 and an associated fv3-jedi PR (tomorrow if we get enough approvals) -- those PRs would make tests work for newest gsibec version.

**Comment by BenjaminTJohnson** [comment]
With apologies, not yet, multiple things going on at home.   I should be
able to get to it later this evening.

**Review by BenjaminTJohnson — APPROVED** [review]

**Comment by BenjaminTJohnson** [comment]
@climbfuji I tested it on S4 with the  CRTM v2.4.1 module and the ufo feature branch for v2.4.1 (feature/btj_v2.4.1_enable), works the same as compiling CRTM v2.4.1 from source.

**Comment by climbfuji** [comment]
> @climbfuji I tested it on S4 with the CRTM v2.4.1 module and the ufo feature branch for v2.4.1 (feature/btj_v2.4.1_enable), works the same as compiling CRTM v2.4.1 from source.

Excellent! Thank you both @BenjaminTJohnson and @shlyaeva for testing this!

**Pull request merged**
