### PR TITLE
Update ip to 4.1.0

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
I'm going to create a spack-stack test branch for this before merging...

## Description

This PR updates ip recipe.

## Issue(s) addressed

Addresses https://github.com/JCSDA/spack-stack/issues/661

## Dependencies

none

## Impact

none

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Did you make any of these changes in spack authoritative already?

**Comment by AlexanderRichert-NOAA** [comment]
Yes-- note commit [58357cc](https://github.com/JCSDA/spack/pull/294/commits/58357ccd326f7bdee55cad67ab050b74eac33113) is based on main spack (https://github.com/spack/spack/pull/38526).

**Comment by climbfuji** [comment]
> Yes-- note commit [58357cc](https://github.com/JCSDA/spack/pull/294/commits/58357ccd326f7bdee55cad67ab050b74eac33113) is based on main spack ([spack#38526](https://github.com/spack/spack/pull/38526)).

I think that update will come in via #295, or at least that PR should come first?

**Comment by AlexanderRichert-NOAA** [comment]
Yes it will, and the order doesn't matter (I don't mind waiting for #295).

**Comment by AlexanderRichert-NOAA** [comment]
Mooted by latest main spack merge.

**Pull request closed without merging**
