### PR TITLE
Add CRTM JEDI release, modify jedi-ufs-env and ufs-weather-model-env, fix FMS version dependencies

### PR DESCRIPTION
**Pull request by climbfuji**
Working towards https://github.com/NOAA-EMC/spack-stack/issues/292.

Unfortunately I don't see a better way than bringing in some explicit dependencies in the environment/convenience packages.

### CODE REVIEW

**Comment by kgerheiser** [comment]
I think this is good. This is how regular packages handle pinned versions. Some other options that are possible are specifying the CRTM version behind a `when=` (develop?), or explictly adding it in the environment specs with `^crtm@2.3.0`.

**Review by kgerheiser — APPROVED** [review]

**Comment by climbfuji** [comment]
unit tests fail because it can't find `jedi-fv3-env`. Is there a way to run unit tests only on packages in the `builtin` repository?

**Comment by climbfuji** [comment]
@kgerheiser I made an attempt to exclude the bundles from the unit tests. Can you check if this makes sense, please?

**Comment by climbfuji** [comment]
> @kgerheiser I made an attempt to exclude the bundles from the unit tests. Can you check if this makes sense, please?

Sigh, that didn't work, I reverted it. We either need to find a way to fix those unit tests, or not run them at all.

**Comment by climbfuji** [comment]
Hmm, for some reason the previously failing unit tests now passed. Will wait for the full CI builds to succeed (and will verify that the correct versions of CRTM and FMS are built and used) before merging this PR.

**Comment by climbfuji** [comment]
CI tests passed: https://github.com/NOAA-EMC/spack-stack/pull/293 - https://github.com/NOAA-EMC/spack-stack/pull/293/commits/c831ea8d98da835ec6c9476df854c51dc1abb527

**Pull request merged**
