### PR TITLE
Newer pythran versions 0.12+ work with newer Intel compilers only for py-scipy

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

As the title says. See https://github.com/JCSDA/spack-stack/pull/589 for a description of the problem.

Tested together with https://github.com/JCSDA/spack-stack/pull/589.

### CODE REVIEW

**Comment by climbfuji** [comment]
@gthompsnJCSDA This means you won't be able to use the plotting scripts that require the Pythran extension in py-scipy on Cheyenne when using the Intel stack - the GNU stack is ok -, or on Casper (only Intel available). Other systems (S4, Orion, ...) are not impacted by this I think, because they use newer Intel compilers.

**Review by ulmononian — APPROVED** [review]
anything over intel 19.99.99 works though?

**Comment by climbfuji** [comment]
> anything over intel 19.99.99 works though?

I don't know exactly - all I know is that the Intel versions we use (classic compilers from oneapi kit), which have versions 2021.3.0 and later, seem to work.

**Comment by climbfuji** [comment]
It's going to be a bit hard to pin this down exactly, honestly, because you'd have to install all different versions between 19.1.1.x on Cheyenne and 2022.0.1 (I tested on Discover).

**Comment by climbfuji** [comment]
I could be more conservative, but I don't like precluding something I haven't tested. Maybe just add a comment that describes what I just replied above?

**Comment by ulmononian** [comment]
> I could be more conservative, but I don't like precluding something I haven't tested. Maybe just add a comment that describes what I just replied above?

i think just adding a comment should suffice for now!

**Comment by climbfuji** [comment]
will do

**Comment by climbfuji** [comment]
Please check again @ulmononian

**Review by ulmononian — APPROVED** [review]

**Pull request merged**
