### PR TITLE
Feature/update spack from authoritative 20221024

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

1. Update the `jcsda_emc_spack_stack` branch from the spack authoritative `develop` branch as of 2022/10/22.

2. Update Python library bug fix from PR https://github.com/NOAA-EMC/spack/pull/185 by moving the code from `config_vars` to `libs` as requested in https://github.com/spack/spack/pull/33410 (see commit 010f1c3689a494ae8aed7eff24dff89731683517, all previous commits are from the authoritative repository).

3. Modify original spack unit tests to work with our way of generating `lmod/lua` modules (no hashes appended to module names and module directory hierarchy) and with our convention to not use uppercase package names in the `packagename_ROOT` variables. See commits bb61a38d8bb3038249f4d4483c595a696dd00b58 and
d3e8d9665d0c01511f59a01451ff5b901bbb4ed2.

4. Update `var/spack/repos/builtin/packages/py-f90nml` and remove `var/spack/repos/jcsda-emc/packages/py-f90nml` (04333058e4fb1c7ddd49848276de0b1a40e66821)

5. Fix `gfortran` patch for `parallelio` by simply making `cmake@3.7:` a dependency for all `parallelio` versions (e230d780970d30a1c53eabae9d0c504f37f63f5b)

6. Bug fix for macOS - cmake's `find_package` doesn't add `libtinfo.dylib` to the ncurses libraries, which now breaks the `eckit` build (e47950bd2ca097dcf0499d0a1b3cbb493d906fbb)

Note 1. I had to manually resolve conflicts in package `parallelio` - we need to test installing multiple versions of the package to make sure everything works as expected. These tests will be part of https://github.com/NOAA-EMC/spack-stack/pull/390.

Note 2. The remaining failing CI tests (see https://github.com/NOAA-EMC/spack/actions/runs/3316953537/jobs/5479312367 and https://github.com/NOAA-EMC/spack/actions/runs/3330453975/jobs/5508968026) to my understanding are not something we did or something that we can fix. When we send back our code to the authoritative repository, we will see if these tests only work there or if something is really not working as expected.

Note 3. We should investigate at some point soon whether we can remove our no-hash-for-modules logic, since apparently spack now has a similar feature.

### CODE REVIEW

**Comment by climbfuji** [comment]
All, can I please have a review of this PR and its associates spack-stack PR? Thanks ...

**Comment by AlexanderRichert-NOAA** [comment]
This looks good to me except I'm not clear on what's going on with the failed tests. If this is due to upstream spack changes, then presumably something needs to get reverted?

**Comment by climbfuji** [comment]
> This looks good to me except I'm not clear on what's going on with the failed tests. If this is due to upstream spack changes, then presumably something needs to get reverted?

The underlying problem is that, since we use spack as a submodule, it is trying to run CI tests that were configured for the spack repository. Those tests only run if files are changed in the `lib` directory (i.e. not the packages, but the spack source code itself). If those tests ran for every commit that we make (usually we only change the packages), they would fail every time.

**Review by AlexanderRichert-NOAA — APPROVED** [review]
Tested basic env setup, installation of weather packages on linux. Looks good.

**Pull request merged**
