### PR TITLE
Start creating cylc packages

### PR DESCRIPTION
**Pull request by kgerheiser**
Got a start on these @climbfuji. Most of the dependent packages are available, but some need to be created still.

For https://github.com/NOAA-EMC/spack-stack/issues/242

### CODE REVIEW

**Comment by climbfuji** [comment]
Wow, great! Thanks for doing that.

**Comment by kgerheiser** [comment]
This is a weird one: https://pypi.org/project/metomi-isodatetime/#modal-close

The URL has an exclamation mark and Spack doesn't like that. Guess it could be pulled from Github instead.

**Comment by kgerheiser** [comment]
I was able to install cylc and cylc-uiserver. No idea if it's all configured properly, but the majority of the work is done.

**Comment by climbfuji** [comment]
@kgerheiser We should try to get this merged before Aug 17.

**Comment by climbfuji** [comment]
I decided to not include this in spack-stack release 1.1.0, but in the following one (1.2.0).

**Pull request closed without merging**
