### PR TITLE
add mepo, update py-pyyaml

### PR DESCRIPTION
**Pull request by mathomp4**
As https://github.com/spack/spack/pull/44879 seems to be weirdly unmergable (?), just in case, I'll make a PR here with the `mepo` update from https://github.com/spack/spack/pull/44879 and the `py-pyyaml` update from https://github.com/spack/spack/pull/44906.

I'll keep monitoring https://github.com/spack/spack/pull/44879 in case that does get in...

### CODE REVIEW

**Comment by climbfuji** [comment]
Since the spack PR was merged, do you want to update this PR so that we have the final version WITH the correct hash from the squashed merged from spack develop?

**Comment by mathomp4** [comment]
> Since the spack PR was merged, do you want to update this PR so that we have the final version WITH the correct hash from the squashed merged from spack develop?

Hmm. Sure...but how would one do that? Always willing to learn new Git routines!

**Comment by climbfuji** [comment]
Start with spack-stack-dev, configure the spack (authoritative) remote, then cherry-pick the squashed-merge hash from the mepo PR. This will give you a lot of conflicts (because we already have a mepo package for v1). Then git checkout "theirs" (i.e. the spack develop version) so that mepo in spack-stack-dev is identical to that in spack develop. "git add", "git commit". That should do?

**Comment by mathomp4** [comment]
Superseded by #448

@climbfuji can you take a look at that?

**Pull request closed without merging**
