### PR TITLE
Bug fix (patch) for nco-5.0.1+ with Intel

### PR DESCRIPTION
**Pull request by climbfuji**
Issue: https://githubhot.com/repo/nco/nco/issues/244

This patch fixes the problem that variable `msk_out` needs to be in the `shared` OMP directive to avoid a compiler error with Intel.

Note: According to the above issue page, it should have been fixed in 5.0.2. I checked the code in 5.0.6 and the bug was still there.

### CODE REVIEW

**Review by kgerheiser — APPROVED** [review]

**Comment by kgerheiser** [comment]
Sorry, I missed this.

**Comment by climbfuji** [comment]
Note that I wrote the patch to apply for anything 5.0.1+ because when I looked (maybe I should have looked twice) 5.0.6 was still having this issue.

**Comment by kgerheiser** [comment]
The build went through for me. Maybe you didn't force re-concretize?

**Comment by climbfuji** [comment]
> The build went through for me. Maybe you didn't force re-concretize?

No, I explicitly installed 5.0.6. But if it went through then we should modify the patch to just apply to 5.0.1.

**Comment by kgerheiser** [comment]
```
==> Installing nco-5.0.6-54gd3lo5l3j5yfwrmnpx47ma45uhtxic
==> No binary for nco-5.0.6-54gd3lo5l3j5yfwrmnpx47ma45uhtxic found: installing from source
==> Fetching https://github.com/nco/nco/archive/5.0.6.tar.gz
==> No patches needed for nco
==> nco: Executing phase: 'autoreconf'
==> nco: Executing phase: 'configure'
==> nco: Executing phase: 'build'
==> nco: Executing phase: 'install'
==> nco: Successfully installed nco-5.0.6-54gd3lo5l3j5yfwrmnpx47ma45uhtxic
```

**Pull request merged**
