### PR TITLE
Add noarch variant to scotch to disable SPACK_TARGET_ARGS

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR fixes a UFS WM RT crash related to Scotch. Apparently, at least on Hera, there's a bug with certain specialized AVX rounding routines that causes a floating point exception in certain UFS WM RTs. I'm open to finding other ways of doing this. I avoided the route of setting the `target` variant for scotch because then spack wants all of its dependencies to have the same target (in this case, x86_64). In hpc-stack, this issue was not occurring because unlike spack-stack, march/mtune were not being set.

Also incorporating bufr v12 recipe update.

Update: There is at least one other package in main Spack (armcomputelibrary) that modifies SPACK_TARGET_ARGS in the recipe, so I hereby cite that as precedent.

### CODE REVIEW

**Review by ulmononian — APPROVED** [review]
awesome & expedient work here, alex.

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji any idea what's up with the unit tests? Did we merge these previously without all of them passing?

**Comment by climbfuji** [comment]
The last PR that was merged was https://github.com/JCSDA/spack/pull/280 and the CI tests passed.

**Comment by climbfuji** [comment]
Is the bufr change cherry-picked from jcsda_emc_spack_stack?

I wonder if the unit tests fail because release/1.4.1 was created from 1.4.0 and not jcsda_emc_spack_stack.

**Comment by AlexanderRichert-NOAA** [comment]
Yes re: cherry-picking.

That was what I meant to ask earlier, is whether there were unit test issues for 1.4.0.

**Comment by climbfuji** [comment]
> Yes re: cherry-picking.
> 
> That was what I meant to ask earlier, is whether there were unit test issues for 1.4.0.

I don't remember there were issues back then, but didn't we (you) pull in some updates from spack authoritative?

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
