### PR TITLE
bugfix/py-cffi for macOS with gcc

### LINKED ISSUE #25: Installation issue: py-cffi on macOS with gcc+gfortran
### Steps to reproduce the issue

On macOS (Monterey) with gcc+gfortran installed via homebrew:
```console
$ spack install py-cffi
```

### Error message

Error is: unknown argument ```-iwithsysroot/usr/include/ffi```

### Information on your system

**WILL BE PROVIDED LATER**

### Additional information

I think I have a fix for it and will create a PR shortly

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by climbfuji**
Fixes #25 by patching `setup.py` when using `gcc` on macOS`.

### CODE REVIEW

**Comment by climbfuji** [comment]
@kgerheiser Please try this.

**Comment by kgerheiser** [comment]
Testing it out now. It's a bit of a pain to get Spack to recognize the patch in my existing build

**Review by kgerheiser — APPROVED** [review]
Patch worked

**Comment by climbfuji** [comment]
> Testing it out now. It's a bit of a pain to get Spack to recognize the patch in my existing build

I hear you. This works for me:
```
spack clean -a
rm -fr envs/MY_ENV/.spack-env/repos/*
rm envs/MY_ENV/spack.lock
spack concretize --reuse
spack install -v --reuse
```

**Comment by climbfuji** [comment]
Thanks for testing!

**Pull request merged**
