### PR TITLE
Add variant to jedi-base-env to enable/disable the build of hdf4 library and pyhdf

### PR DESCRIPTION
**Pull request by srherbener**
This PR adds a variant to the jedi-base-env to add the ability to enable or disable the build of the hdf4 library and the pyhdf python package. By default the build of hdf4/pyhdf are enabled.

The hdf4 library is very old and can be problematic building it on some platforms (recently had issues with MacOS with the Arm architecture). Plus the hdf4/pyhdf combination is only required for a single ioda converter and not used anywhere else meaning that it is not detrimental to disable these packages. Ie, the absence of hdf4/pyhdf does not impact ewok experiments.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Looks good. I assume you have tested turning off hdf with the new variant?

**Comment by srherbener** [comment]
> Looks good. I assume you have tested turning off hdf with the new variant?

Yes. I used the following steps to test disabling hdf4/pyhdf:

Before running concretize and install:
- `spack config add "packages:jedi-base-env:variants:~hdf5"`
- edit "envs/skylab.macos/spack.yaml"
    - Comment out the line "- hdf@1.12.1"

Then concretize and install successfully ran to completion and hdf4/pyhdf were absent from the stack.

**Comment by srherbener** [comment]
I'm seeing the following error in the `rhel8-platform-python` test:
```
...
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lib/spack/spack/util/gpg.py:73: in init
    os.makedirs(GNUPGHOME)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = '/__w/spack/spack/opt/spack/gpg', mode = 511, exist_ok = False

    def makedirs(name, mode=0o777, exist_ok=False):
        """makedirs(name [, mode=0o777][, exist_ok=False])
    
        Super-mkdir; create a leaf directory and all intermediate ones.  Works like
        mkdir, except that any intermediate path segment (not just the rightmost)
        will be created if it does not exist. If the target directory already
        exists, raise an OSError if exist_ok is False. Otherwise no exception is
        raised.  This is recursive.
    
        """
        head, tail = path.split(name)
        if not tail:
            head, tail = path.split(head)
        if head and tail and not path.exists(head):
            try:
                makedirs(head, mode, exist_ok)
            except FileExistsError:
                # Defeats race condition when another thread created the path
                pass
            cdir = curdir
            if isinstance(tail, bytes):
                cdir = bytes(curdir, 'ASCII')
            if tail == cdir:           # xxx/newdir/. exists if xxx/newdir exists
                return
        try:
>           mkdir(name, mode)
E           PermissionError: [Errno 13] Permission denied: '/__w/spack/spack/opt/spack/gpg'

/usr/lib64/python3.6/os.py:220: PermissionError
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
============================= 21 tests deselected ==============================
======== 117 passed, 5 skipped, 21 deselected, 1 error in 29.80 seconds ========
Error: Process completed with exit code 2.
```

Is that something I need to address in my PR? Thanks!

**Comment by climbfuji** [comment]
That's ok. We should really turn off this test in our fork, it's not supposed to work outside the authoritative spack repository.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
