### PR TITLE
Add MET v11.0.0 and v11.0.1

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
Adding latest MET versions.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Same comment as for https://github.com/NOAA-EMC/spack/pull/234: We need to test building those on macOS and Linux before we make the new version the default for our environments. Can we work on and complete https://github.com/NOAA-EMC/spack-stack/pull/463 first so that we have a working CI setup with at least one compiler for each macOS and Linux?

**Comment by AlexanderRichert-NOAA** [comment]
Yes, agree

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA FYI See https://github.com/dtcenter/METplus/discussions/2127 and https://github.com/dtcenter/MET/issues/2514

**Review by climbfuji — APPROVED** [review]
This PR was tested with https://github.com/NOAA-EMC/spack-stack/pull/574 (draft PR, will not be merged, submodule pointer update will happen in a subsequent PR in spack-stack). CI tests pass, because the new met versions are not yet used.

**Comment by climbfuji** [comment]
This PR was tested with https://github.com/NOAA-EMC/spack-stack/pull/574 (draft PR, will not be merged, submodule pointer update will happen in a subsequent PR in spack-stack). CI tests pass, because the new met versions are not yet used.

**Pull request merged**
