### PR TITLE
Bug fixes and updates of maintainers for ESMF and MAPL

### LINKED ISSUE #312: esmf@8.3.0b09 pio variant error after recent update
**Describe the bug**
After yesterday's merge of the ESMF update, we can't install esmf@8.3.0b09 with pio anymore.

Version esmf@8.3.0b09 still uses pio the "old" way (i.e. it uses its own, old internal version of pio), but the way the variants are encoded make spack treat esmf@8.3.0b09 same as esmf@8.3.0 (a recurring problem with the esmf beta snapshot naming schemes), i.e. it expects an option parallelio to enable the parallelio interface using an external (=spack) parallelio installation.

**To Reproduce**
Tro to install esmf@8.3.0b09+pio or esmf@8.3.0b09+parallelio - neither will work.

**Expected behavior**
esmf@8.3.0b09+pio installs that version of ESMF with internal parallelio.

**System:**
Any system.

**Additional context**
I have a pretty nasty workaround for this problem:
```
diff --git a/var/spack/repos/builtin/packages/esmf/package.py b/var/spack/repos/builtin/packages/esmf/package.py
index 814384cd73..7a9ff43ad1 100644
--- a/var/spack/repos/builtin/packages/esmf/package.py
+++ b/var/spack/repos/builtin/packages/esmf/package.py
@@ -303,7 +303,13 @@ def edit(self, spec, prefix):
         ##############
         # ParallelIO #
         ##############
-        if "+parallelio" in spec and "+mpi" in spec:
+        # Nasty workaround for version 8.3.0b09 ...
+        if "@8.3.0b09" in spec:
+            if "+parallelio" in spec:
+                os.environ["ESMF_PIO"] = "internal"
+            else:
+                os.environ["ESMF_PIO"] = "OFF"
+        elif "+parallelio" in spec and "+mpi" in spec:
             os.environ["ESMF_PIO"] = "external"
             os.environ["ESMF_PIO_LIBPATH"] = spec["parallelio"].prefix.lib
             os.environ["ESMF_PIO_INCLUDE"] = spec["parallelio"].prefix.include
```
This way, one can install esmf@8.3.0b09+parallelio (using an internal parallelio - misleading and confusing, but it works).

### LINKED ISSUE #313: Once again mapl@2.22.0 build errors on macOS
**Describe the bug**
mapl@2.22.0 no longer builds on my macOS with clang+gfortran. There has been no change to the mapl package itself. But there was a recent update from the authoritative spack-repository, which apparently changed something in the concretization step. As a result, the ufs-weather-model-env wants to use esmf@8.2.0 (instead of esmf@8.3.0b09) with mapl@2.22.0, and I a wondering if this has to do with the error (although the error to me looks different).

**To Reproduce**
Try to install the `skylab-dev` template on macOS. This uses mapl@2.22.0 and also explicitly asks for esmf@8.3.0b09, but the ufs-weather-model-env tries to build with esmf@8.2.0 and mapl@2.22.0. Not sure if this is the problem. The error is:
```
[  5%] Built target MAPL.constants
make: *** [all] Error 2
==> Error: ProcessError: Command exited with status 2:
    'make' '-j10'

7 errors found in build log:
     192    [  1%] Building Fortran object MAPL_cfio_r8/CMakeFiles/MAPL_cfio_r8.dir/ESMF_CFIOBaseMod.f.o
     193    cd /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/MAPL_cfio_r8 && /Users/heinzell/work/sp
            ack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/openmpi-4.1.4-eyvbtzt/bin/mpif90 -DFORTRAN_COMPILER_SUPPORTS_ASSUMED_TYPE -DFORTRAN_COMPILER_SUPPORTS_FI
            NDLOC -DH5_HAVE_PARALLEL -DHAS_NETCDF3 -DHAS_NETCDF4 -DMAPL_cfio_r8_EXPORTS -DNETCDF_NEED_NF_MPIIO -D__GFORTRAN__ -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spa
            ck-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/MAPL_cfio -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehju
            ydenmxged4nks/spack-build-vm3trpm/MAPL_cfio_r8 -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-v
            m3trpm/include/MAPL_cfio_r8 -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/netcdf-fortran-4.5.4-mpp2zhv/include -ffree-line-le
            ngth-none -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.0 -J../include/MAPL_cfio_r8 -fPIC -fdefault-real-8 -fdefault-double-8 -fallow-arg
            ument-mismatch -O -m64 -mcmodel=small -ffree-line-length-none -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/esmf-8.2.0-eqwvrt
            5/include -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/netcdf-c-4.8.1-zbvzadn/include -I/Users/heinzell/work/spack-stack/upd
            ate-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/netcdf-fortran-4.5.4-mpp2zhv/include -DESMF_NO_INTEGER_1_BYTE -DESMF_NO_INTEGER_2_BYTE -DESMF_MOAB=1 -DESMF_LAPACK=1
            -DESMF_LAPACK_INTERNAL=1 -DESMF_NO_ACC_SOFTWARE_STACK=1 -DESMF_NETCDF=1 -DESMF_YAMLCPP=1 -DESMF_YAML=1 -DESMF_PIO=1 -DESMF_MPIIO -DESMF_NO_PTHREADS -DESMF_NO_OPENMP -DESMF_NO_OPENACC -DESMF_BOPT_O -DESMF_TESTCOMPTUNNEL -DSx86_64_small=1 -DE
            SMF_OS_Darwin=1 -DESMF_COMM=openmpi -DESMF_DIR=/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-esmf-8.2.0-eqwvrt5pakty6jetp6iu3mcagno4vyoo/spack-src -c /Us
            ers/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/MAPL_cfio/ESMF_CFIOBaseMod.f -o CMakeFiles/MAPL_cfio_r8
            .dir/ESMF_CFIOBaseMod.f.o
     194    [  1%] Building C object MAPL_cfio_r8/CMakeFiles/MAPL_cfio_r8.dir/ShaveMantissa.c.o
     195    [  2%] Building C object MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ShaveMantissa.c.o
     196    cd /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/MAPL_cfio_r8 && /Users/heinzell/work/sp
            ack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/openmpi-4.1.4-eyvbtzt/bin/mpicc -DFORTRAN_COMPILER_SUPPORTS_ASSUMED_TYPE -DFORTRAN_COMPILER_SUPPORTS_FIN
            DLOC -DH5_HAVE_PARALLEL -DHAS_NETCDF3 -DHAS_NETCDF4 -DMAPL_cfio_r8_EXPORTS -DNETCDF_NEED_NF_MPIIO -D__GFORTRAN__ -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spac
            k-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/MAPL_cfio -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuy
            denmxged4nks/spack-build-vm3trpm/MAPL_cfio_r8 -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm
            3trpm/include/MAPL_cfio_r8 -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/netcdf-fortran-4.5.4-mpp2zhv/include -pipe -O2 -g -D
            NDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.0 -fPIC -fallow-argument-mismatch -O -m64 -mcmodel=small -ffree-line-length-none -I/Use
            rs/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/esmf-8.2.0-eqwvrt5/include -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-
            from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/netcdf-c-4.8.1-zbvzadn/include -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/e
            nvs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/netcdf-fortran-4.5.4-mpp2zhv/include -DESMF_NO_INTEGER_1_BYTE -DESMF_NO_INTEGER_2_BYTE -DESMF_MOAB=1 -DESMF_LAPACK=1 -DESMF_LAPACK_INTERNAL=1 -DESMF_NO_ACC_SOFTWARE_STACK=1 -DESMF_NETCD
            F=1 -DESMF_YAMLCPP=1 -DESMF_YAML=1 -DESMF_PIO=1 -DESMF_MPIIO -DESMF_NO_PTHREADS -DESMF_NO_OPENMP -DESMF_NO_OPENACC -DESMF_BOPT_O -DESMF_TESTCOMPTUNNEL -DSx86_64_small=1 -DESMF_OS_Darwin=1 -DESMF_COMM=openmpi -DESMF_DIR=/Users/heinzell/work/
            spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-esmf-8.2.0-eqwvrt5pakty6jetp6iu3mcagno4vyoo/spack-src -MD -MT MAPL_cfio_r8/CMakeFiles/MAPL_cfio_r8.dir/ShaveMantissa.c.o -MF CMa
            keFiles/MAPL_cfio_r8.dir/ShaveMantissa.c.o.d -o CMakeFiles/MAPL_cfio_r8.dir/ShaveMantissa.c.o -c /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.
            0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/MAPL_cfio/ShaveMantissa.c
     197    cd /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/MAPL_cfio_r4 && /Users/heinzell/work/sp
            ack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/openmpi-4.1.4-eyvbtzt/bin/mpicc -DFORTRAN_COMPILER_SUPPORTS_ASSUMED_TYPE -DFORTRAN_COMPILER_SUPPORTS_FIN
            DLOC -DH5_HAVE_PARALLEL -DHAS_NETCDF3 -DHAS_NETCDF4 -DMAPL_cfio_r4_EXPORTS -DNETCDF_NEED_NF_MPIIO -D__GFORTRAN__ -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spac
            k-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/MAPL_cfio -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuy
            denmxged4nks/spack-build-vm3trpm/MAPL_cfio_r4 -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm
            3trpm/include/MAPL_cfio_r4 -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/netcdf-fortran-4.5.4-mpp2zhv/include -pipe -O2 -g -D
            NDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.0 -fPIC -fallow-argument-mismatch -O -m64 -mcmodel=small -ffree-line-length-none -I/Use
            rs/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/esmf-8.2.0-eqwvrt5/include -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-
            from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/netcdf-c-4.8.1-zbvzadn/include -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/e
            nvs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/netcdf-fortran-4.5.4-mpp2zhv/include -DESMF_NO_INTEGER_1_BYTE -DESMF_NO_INTEGER_2_BYTE -DESMF_MOAB=1 -DESMF_LAPACK=1 -DESMF_LAPACK_INTERNAL=1 -DESMF_NO_ACC_SOFTWARE_STACK=1 -DESMF_NETCD
            F=1 -DESMF_YAMLCPP=1 -DESMF_YAML=1 -DESMF_PIO=1 -DESMF_MPIIO -DESMF_NO_PTHREADS -DESMF_NO_OPENMP -DESMF_NO_OPENACC -DESMF_BOPT_O -DESMF_TESTCOMPTUNNEL -DSx86_64_small=1 -DESMF_OS_Darwin=1 -DESMF_COMM=openmpi -DESMF_DIR=/Users/heinzell/work/
            spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-esmf-8.2.0-eqwvrt5pakty6jetp6iu3mcagno4vyoo/spack-src -MD -MT MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ShaveMantissa.c.o -MF CMa
            keFiles/MAPL_cfio_r4.dir/ShaveMantissa.c.o.d -o CMakeFiles/MAPL_cfio_r4.dir/ShaveMantissa.c.o -c /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.
            0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/MAPL_cfio/ShaveMantissa.c
  >> 198    clang: error: unknown argument: '-fallow-argument-mismatch'
  >> 199    clang: error: unknown argument: '-fallow-argument-mismatch'
  >> 200    make[2]: *** [MAPL_cfio_r8/CMakeFiles/MAPL_cfio_r8.dir/ShaveMantissa.c.o] Error 1
     201    make[2]: *** Waiting for unfinished jobs....
  >> 202    make[2]: *** [MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/ShaveMantissa.c.o] Error 1
     203    make[2]: *** Waiting for unfinished jobs....
     204    -dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/shared/Constants /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build
            _stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/shared/Constants/CMakeFiles/MAPL.constants.dir/DependInfo.cmake --color=
     205    /usr/local/Cellar/cmake/3.23.1/bin/cmake -E cmake_copy_f90_mod include/pflogger/pfl_keywordenforcermod.mod pflogger_stub/CMakeFiles/pflogger.dir/pfl_keywordenforcermod.mod.stamp GNU
     206    /usr/local/Cellar/cmake/3.23.1/bin/cmake -E touch pflogger_stub/CMakeFiles/pflogger.dir/PFL_KeywordEnforcer.F90.o.provides.build
     207    Scanning dependencies of target MAPL.constants
     208    /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f shared/Constants/CMakeFiles/MAPL.constants.dir/build.make shared/Constants/CMakeFiles/MAPL.constants.dir/build
  >> 209    make[1]: *** [MAPL_cfio_r4/CMakeFiles/MAPL_cfio_r4.dir/all] Error 2
     210    make[1]: *** Waiting for unfinished jobs....
  >> 211    make[1]: *** [MAPL_cfio_r8/CMakeFiles/MAPL_cfio_r8.dir/all] Error 2
     212    [  3%] Building Fortran object shared/Constants/CMakeFiles/MAPL.constants.dir/MathConstants.F90.o
     213    [  3%] Building Fortran object shared/Constants/CMakeFiles/MAPL.constants.dir/InternalConstants.F90.o
     214    cd /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/shared/Constants && /Users/heinzell/wor
            k/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/openmpi-4.1.4-eyvbtzt/bin/mpif90 -DFORTRAN_COMPILER_SUPPORTS_ASSUMED_TYPE -DFORTRAN_COMPILER_SUPPORT
            S_FINDLOC -DH5_HAVE_PARALLEL -DHAS_NETCDF3 -DHAS_NETCDF4 -DMAPL_constants_EXPORTS -DNETCDF_NEED_NF_MPIIO -D__GFORTRAN__ -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_sta
            ge/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/shared/Constants -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trp
            mjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/shared/Constants -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4
            nks/spack-build-vm3trpm/include/MAPL.constants -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/inc
            lude -ffree-line-length-none -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.0 -J../../include/MAPL.constants -fPIC -c /Users/heinzell/work
            /spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/shared/Constants/MathConstants.F90 -o CMakeFiles/MAPL.constants.dir/Math
            Constants.F90.o
     215    /usr/local/Cellar/cmake/3.23.1/bin/cmake -E cmake_copy_f90_mod include/pflogger/pfl_wraparray.mod pflogger_stub/CMakeFiles/pflogger.dir/pfl_wraparray.mod.stamp GNU
     216    cd /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/shared/Constants && /Users/heinzell/wor
            k/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/openmpi-4.1.4-eyvbtzt/bin/mpif90 -DFORTRAN_COMPILER_SUPPORTS_ASSUMED_TYPE -DFORTRAN_COMPILER_SUPPORT
            S_FINDLOC -DH5_HAVE_PARALLEL -DHAS_NETCDF3 -DHAS_NETCDF4 -DMAPL_constants_EXPORTS -DNETCDF_NEED_NF_MPIIO -D__GFORTRAN__ -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_sta
            ge/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/shared/Constants -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trp
            mjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/shared/Constants -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4
            nks/spack-build-vm3trpm/include/MAPL.constants -I/Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/inc
            lude -ffree-line-length-none -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.0 -J../../include/MAPL.constants -fPIC -c /Users/heinzell/work
            /spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-src/shared/Constants/InternalConstants.F90 -o CMakeFiles/MAPL.constants.dir/
            InternalConstants.F90.o
     217    /usr/local/Cellar/cmake/3.23.1/bin/cmake -E touch pflogger_stub/CMakeFiles/pflogger.dir/WrapArray.F90.o.provides.build

     ...

     246    cd /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/shared/Constants && /usr/local/Cellar/c
            make/3.23.1/bin/cmake -E remove /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/lib/libMAP
            L.constants.dylib
     247    cd /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/cache/build_stage/spack-stage-mapl-2.22.0-vm3trpmjvmiv5cuehjuydenmxged4nks/spack-build-vm3trpm/shared/Constants && /usr/local/Cellar/c
            make/3.23.1/bin/cmake -E cmake_link_script CMakeFiles/MAPL.constants.dir/link.txt --verbose=1
     248    /Users/heinzell/work/spack-stack/update-noaa-spack-fork-from-develop-20220815/spack-stack-dev-20220815/envs/skylab-dev-rpath-test-2/install/apple-clang/13.1.6/openmpi-4.1.4-eyvbtzt/bin/mpif90 -ffree-line-length-none -O2 -g -DNDEBUG -isysroo
            t /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.0 -dynamiclib -Wl,-headerpad_max_install_names -o ../../lib/libMAPL.constants.dylib -install_name @rpath/libMAPL.co
            nstants.dylib CMakeFiles/MAPL.constants.dir/InternalConstants.F90.o CMakeFiles/MAPL.constants.dir/MathConstants.F90.o CMakeFiles/MAPL.constants.dir/PhysicalConstants.F90.o CMakeFiles/MAPL.constants.dir/Constants.F90.o
     249    ld: warning: dylib (/usr/local/Cellar/gcc/11.3.0/lib/gcc/11/libquadmath.dylib) was built for newer macOS version (12.2) than being linked (12.0)
     250    ld: warning: dylib (/usr/local/Cellar/gcc/11.3.0/lib/gcc/11/libgfortran.dylib) was built for newer macOS version (12.2) than being linked (12.0)
     251    [  5%] Built target MAPL.constants
  >> 252    make: *** [all] Error 2
```
I looked into the CMakeCache files, CMakeFiles directories etc and it adds the Fortran flag `-fallow-argument-mismatch` to the C flags, which if course doesn't work. I couldn't spot immediately what is wrong from the `CMakeLists.txt` file that contains the offending C file `ShaveMantissa.c`.

**Expected behavior**
mapl installs on macOS (once and for all ...)

**System:**
macOS Monterey with apple-clang@13.1.6 and gfortran@11.3.0

**Additional context**
mapl@2.12.3 installs just fine in the same environment

### PR DESCRIPTION
**Pull request by climbfuji**
- `var/spack/repos/builtin/packages/esmf/package.py`: add @jedwards4b as maintainer, bug fix for using internal PIO with version `8.3.0b09`
- `var/spack/repos/jcsda-emc/packages/mapl/package.py`: add @mathomp4 and @climbfuji as maintainers, bug fix for `mapl@2.22.0` - depends on recent ESMF versions

Note. The Linux style tests are currently failing, because `black` wants to reformat the mapl package (replace all single quotes with double quotes etc.). I will make this change *after* the code has been reviewed, because once I make the change it will be difficult to infer what the actual code changes are.

Fixes https://github.com/NOAA-EMC/spack-stack/issues/313
Fixes https://github.com/NOAA-EMC/spack-stack/issues/312

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]

**Comment by climbfuji** [comment]
@mathomp4 Do you have any comments/suggestions for this PR, in particular for adding you as maintainer for `mapl`?

**Comment by srherbener** [comment]
I'm testing this on my Mac now.

**Comment by mathomp4** [comment]
> @mathomp4 Do you have any comments/suggestions for this PR, in particular for adding you as maintainer for `mapl`?

@climbfuji I think your changes look good. 

Eventually, I'll want to add changes based on my testing with my own MAPL spack package but we can feed those in over time until you can test. For example, I think we'd want to build to:

```python
    # There was an interface change in yaFyaml, so we need to control versions
    # MAPL 2.22 and older uses older version, MAPL 2.23+ and higher uses newer
    depends_on('yafyaml@1.0-beta5', when='@:2.22')
    depends_on('yafyaml@1.0.4:', when='@2.23:')

    # pFlogger depends on yaFyaml in the same way. MAPL 2.22 and below uses old
    # yaFyaml so we need to use old pFlogger, but MAPL 2.23+ uses new yaFyaml
    depends_on('pflogger@:1.6', when='@:2.22+pflogger')
    depends_on('pflogger@1.9.1:', when='@2.23:+pflogger')
```

so that old and new work. But we might need to wait until I can add in the GFE packages more comprehensively.

And from thinking on that your `yaFyaml` does seem a bit old:
```python
    depends_on('yafyaml@:0.5.1')
```
At least for recent times, as you see above, I'd recommend 1.0-beta5 for 2.22 (it's what we used) and then 1.0.4 after that. I *think* it would work okay for even older MAPL as well, but I'd need to consult with @tclune on that.

**Comment by tclune** [comment]
The interfaces did change in the 1.0 releases and varied a bit within the 1.0 beta releases.   So the answer depends on the client code.  My recommendation is to update to latest yafyaml and update the client code accordingly.  Not trivial, but not hard either.  We can help.

**Comment by climbfuji** [comment]
> The interfaces did change in the 1.0 releases and varied a bit within the 1.0 beta releases. So the answer depends on the client code. My recommendation is to update to latest yafyaml and update the client code accordingly. Not trivial, but not hard either. We can help.

Thanks @tclune and @mathomp4 . Given that newer versions of `yafyaml` require interface changes in submodules of the ufs-weather-model (@edwardhartnett @Hang-Lei-NOAA please take note) that are outside of my purview, would you be ok to approve this PR and keep `yafyaml@0.5.1` for now?

**Review by mathomp4 — APPROVED** [review]

**Comment by climbfuji** [comment]
Thanks @mathomp4 - now that the actual code changes have been reviewed, I'll add the `black` formatting changes.

**Comment by climbfuji** [comment]
`black` is now happy, going to merge

**Pull request merged**
