### PR TITLE
Add latest versions to METplus

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
Adding v5.0.1 and v5.0.0 to METplus, changing maintainer to me.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
We need to test building those on macOS and Linux before we make the new version the default for our environments. Can we work on and complete https://github.com/NOAA-EMC/spack-stack/pull/463 first so that we have a working CI setup with at least one compiler for each macOS and Linux?

**Comment by AlexanderRichert-NOAA** [comment]
Yep fine with me. The met, metplus, and MADIS PRs are not urgent.

**Review by climbfuji — CHANGES_REQUESTED** [review]
Can you create a spack-stack PR for this and update the defaults in the common configs? I had build failures for at least newer met versions (11.x on macOS). But maybe metplus 5.x alone is fine with met 10.x.

**Comment by AlexanderRichert-NOAA** [comment]
Yep will do

**Comment by climbfuji** [comment]
Thanks!

**Review by climbfuji — APPROVED** [review]
This was tested successfully with draft PR https://github.com/NOAA-EMC/spack-stack/pull/571 (we'll close the PR, it was created just for testing), commit https://github.com/NOAA-EMC/spack-stack/pull/571/commits/d40336f982c02aeb08bcf4f014c23670bbe7897b. The failing readthedocs build can be ignored, because there is another PR in the works https://github.com/NOAA-EMC/spack-stack/pull/555 that will
- fix the readthedocs build
- and update the submodule pointer for spack to include the metplus update

**Pull request merged**
