### PR TITLE
Adding ecmwf-atlas version 0.38

### PR DESCRIPTION
**Pull request by ericlingerfelt**
Adding versions 0.38.0 and 0.38.1 for ecmwf-atlas.

### CODE REVIEW

**Comment by climbfuji** [comment]
For CI testing, see https://github.com/JCSDA/spack/pull/453

**Comment by climbfuji** [comment]
The corresponding spack develop PR was just merged; can you confirm that you cherry-picked the commit, i.e. same commit hash for our fork and spack develop?

**Comment by srherbener** [comment]
@climbfuji good call! It looks like the commits don't match.
This PR: 481185b750f99dcfe1ef8ffb2a929a7880124a1f
Authoritative spack PR: 0b2e0a54710c851fe48a1c1f3086fb7cc1961aff

Not sure what went wrong. What's the recommended way to fix this? Thanks!

**Comment by climbfuji** [comment]
> @climbfuji good call! It looks like the commits don't match. This PR: [481185b](https://github.com/JCSDA/spack/commit/481185b750f99dcfe1ef8ffb2a929a7880124a1f) Authoritative spack PR: [0b2e0a5](https://github.com/JCSDA/spack/commit/0b2e0a54710c851fe48a1c1f3086fb7cc1961aff)
> 
> Not sure what went wrong. What's the recommended way to fix this? Thanks!

Abandon this PR and cherry-pick the commit from spack develop probably?

**Comment by srherbener** [comment]
@climbfuji sounds good. I'll close this PR and start over.

**Pull request closed without merging**
