### PR TITLE
Add esmf@8.4.1, apply patch for "gcc: permission denied" error on MSU Hercules, cherry-pick ESMF PRs from authoritative repo

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

All in the title, and all for ESMF:
- Add esmf@8.4.1
- Apply patch for "gcc: permission denied" error on MSU Hercules (see https://github.com/spack/spack/issues/35957), cherry-picked from https://github.com/spack/spack/pull/35969/commits/361452074c968d2add079917035d9c382b93199f
- Cherry-pick ESMF PR from authoritative repo, take 1: https://github.com/spack/spack/pull/35249 (Use setup_build_environment instead of edit in esmf/package.py)
- Cherry-pick ESMF PR from authoritative repo, take 2: https://github.com/spack/spack/pull/36087 (Fix for ESMF post_install on macOS)

## Issues

See https://github.com/spack/spack/issues/35957 (I won't mark it as "fixes" here, that will be the corresponding PR in the authoritative repository).

## Testing

Tested successfully on MSU Hercules.

### CODE REVIEW

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @GeorgeVandenberghe-NOAA @jedwards4b This PR is ready for merging. It cherry-picks the updates from the authoritative spack repo, there won't be any merge conflicts down the road.

**Comment by ulmononian** [comment]
should the issue raised by @mathomp4 regarding the esmf libs patch on macos be included here? (sounded like a pr to spack for cherry-picking is in the works).

**Comment by mathomp4** [comment]
> should the issue raised by @mathomp4 regarding the esmf libs patch on macos be included here? (sounded like a pr to spack for cherry-picking is in the works).

@ulmononian Yeah, I wasn't sure how to do it. I figured the "right" thing to do is get it to mainline spack, but then also add it here? I just didn't want to screw up any ongoing PRs!

ETA: PR to spack is here: https://github.com/spack/spack/pull/36087

**Comment by ulmononian** [comment]
@mathomp4 thanks for getting that pr in. i'd say it is up to @climbfuji if the cherry-pick of your fix should be included here or in a forthcoming pr.

**Comment by climbfuji** [comment]
> @mathomp4 thanks for getting that pr in. i'd say it is up to @climbfuji if the cherry-pick of your fix should be included here or in a forthcoming pr.

I'll cherry-pick it and add it here.

**Review by ulmononian — APPROVED** [review]

**Comment by climbfuji** [comment]
@mathomp4 I cherry-picked your PR to the authoritative repo.

**Comment by mathomp4** [comment]
> @mathomp4 I cherry-picked your PR to the authoritative repo.

Of course, if it's like any of my other spack PRs, it'll have a good number of proposed changes for style, etc. 😄

**Comment by climbfuji** [comment]
> > @mathomp4 I cherry-picked your PR to the authoritative repo.
> 
> Of course, if it's like any of my other spack PRs, it'll have a good number of proposed changes for style, etc. 😄

If so, those can be added later. We need the spack-stack release ready by the end of the week, and for this we'll need the two PRs from the authoritative repos integrated here (functionally at least).

**Review by mathomp4 — APPROVED** [review]
Well, the one bit I know about looks good. I haven't tried the rest, but I trust in @climbfuji

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @jedwards4b Can we merge this and approve the two PRs in the authoritative spack repo from which this PR here cherry-picked?

https://github.com/spack/spack/pull/36087
https://github.com/spack/spack/pull/35969

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji Yep looks good to me

**Review by jedwards4b — APPROVED** [review]

**Pull request merged**
