### PR TITLE
Update ESMF to support clang with gfortran and clang with flang (spack #48026); replace esmf@8.8.0b06 with esmf@8.8.0b10

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

So far, the ESMF package recipe in spack assumes that the spack compilers clang and apple-clang are using gfortran as the Fortran compiler. But with the latest improvements to the LLVM compilers, we need to also support clang with flang. See https://github.com/spack/spack/pull/48026 for more information and feedback from the package maintainers and spack developers if there's a better way (PR was reviewed and merged Dec 11, 2024).

Also add `esmf@8.8.0b09` (seems to be necessary for LLVM 19.1.4; regardless, both NEPTUNE and UFS need this version).

See https://github.com/JCSDA/spack-stack/pull/1409 for the corresponding spack-stack PR (this PR has some unrelated changes = cleanup on Derecho and is therefore still in draft; however, ESMF works as expected in CI and my manual testing with LLVM 19.1.4 on my dev machine).

### CODE REVIEW

**Review by theurich — COMMENTED** [review]
Changes look good. However, I think it would be good to wait with this PR until Monday (12/16/24) when we expect to have v8.8.0b10 tagged. This will be the feature frozen code tag for the official 8.8.0 release (expected by mid Jan. 2025).

**Comment by climbfuji** [comment]
> Changes look good. However, I think it would be good to wait with this PR until Monday (12/16/24) when we expect to have v8.8.0b10 tagged. This will be the feature frozen code tag for the official 8.8.0 release (expected by mid Jan. 2025).

Ok, fine with me.

**Comment by theurich** [comment]
@climbfuji https://github.com/esmf-org/esmf/releases/tag/v8.8.0b10 is available. This is the feature frozen code for the upcoming official ESMF 8.8.0 release.

**Review by theurich — APPROVED** [review]
Verified commit hash. Looks good.

**Pull request merged**
