### PR TITLE
Update jcsda_emc_spack_stack from spack develop 2022/12/22

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Update our spack branch `jcsda_emc_spack_stack` with the changes from upstream as of 2022/12/22. This includes many small updates. As part of these, and in order to reduce differences between the upstream repository and our branch, I cleaned up a few packages and removed `awscli` from `jedi-tools-env`. Please check the last six commits, starting from 33d6668b482986c73ab2a8be93cbee85ed0109b1.

## Testing

See https://github.com/NOAA-EMC/spack-stack/pull/424

## Issues

Working towards https://github.com/NOAA-EMC/spack/issues/209.

### CODE REVIEW

**Comment by mathomp4** [comment]
Ooh commit [ea2c61c](https://github.com/NOAA-EMC/spack/pull/210/commits/ea2c61c6831d3d82eef6c5d6a2444e1482368070) looks familiar 😄

**Comment by climbfuji** [comment]
> Ooh commit [ea2c61c](https://github.com/NOAA-EMC/spack/pull/210/commits/ea2c61c6831d3d82eef6c5d6a2444e1482368070) looks familiar 😄

Which reminds me that there may now be duplicate packages in the `jcsda-emc` subdirectory that we should remove?

**Comment by mathomp4** [comment]
> > Ooh commit [ea2c61c](https://github.com/NOAA-EMC/spack/pull/210/commits/ea2c61c6831d3d82eef6c5d6a2444e1482368070) looks familiar 😄
> 
> Which reminds me that there may now be duplicate packages in the `jcsda-emc` subdirectory that we should remove?

Well, from that PR to mainline it'd be `yafyaml` and `gftl-shared`. I'm *pretty* sure it should be just fine as my updates were sort of "on top" of your packages. And I think I just added versions but didn't remove any you all had.

**Comment by climbfuji** [comment]
Ok, let me push the removal of these packages from the jcsda-emc directory when the CI tests either passed or failed and I need to make other changes

**Comment by climbfuji** [comment]
> > > Ooh commit [ea2c61c](https://github.com/NOAA-EMC/spack/pull/210/commits/ea2c61c6831d3d82eef6c5d6a2444e1482368070) looks familiar 😄
> > 
> > 
> > Which reminds me that there may now be duplicate packages in the `jcsda-emc` subdirectory that we should remove?
> 
> Well, from that PR to mainline it'd be `yafyaml` and `gftl-shared`. I'm _pretty_ sure it should be just fine as my updates were sort of "on top" of your packages. And I think I just added versions but didn't remove any you all had.

Done in https://github.com/NOAA-EMC/spack/pull/210/commits/8322daf5787d4fc122b183360dfc2037da7bac0e - let's see if that builds in CI and on my local macOS!

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA This is a big PR, but the only commits that need to be checked are the last six commits, starting from https://github.com/NOAA-EMC/spack/commit/33d6668b482986c73ab2a8be93cbee85ed0109b1. Thanks a lot in advance!

**Comment by AlexanderRichert-NOAA** [comment]
> @AlexanderRichert-NOAA This is a big PR, but the only commits that need to be checked are the last six commits, starting from [33d6668](https://github.com/NOAA-EMC/spack/commit/33d6668b482986c73ab2a8be93cbee85ed0109b1). Thanks a lot in advance!

Yep, reviewing right now, thanks!

**Review by mathomp4 — APPROVED** [review]
All changes from https://github.com/NOAA-EMC/spack/commit/33d6668b482986c73ab2a8be93cbee85ed0109b1 on look fine to me.

**Review by AlexanderRichert-NOAA — APPROVED** [review]
Thumbs up

**Pull request merged**
