### PR TITLE
Add capitalized symlinks for ESMF libs

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
Pulling in commits from main spack for adding libESMF.{a,so} symlinks.

### CODE REVIEW

**Comment by ulmononian** [comment]
this is really timely because i was just going to ask @climbfuji to make this symlink in the orion UE install's $esmf_ROOT/libs.

thank you for doing this!!

**Review by ulmononian — APPROVED** [review]

**Comment by ulmononian** [comment]
@AlexanderRichert-NOAA one thing: i assume you tested an esmf install w/ this post_install function and it properly linked the libs?

**Comment by AlexanderRichert-NOAA** [comment]
@ulmononian Yes I did

**Comment by ulmononian** [comment]
> @ulmononian Yes I did

awesome. light at the end of the tunnel.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
