### PR TITLE
Merge authoritative spack develop into noaa-emc/jcsda_emc_spack_stack

### PR DESCRIPTION
**Pull request by climbfuji**
As the title says: merge authoritative spack develop into noaa-emc/jcsda_emc_spack_stack.

This is needed to solve the issues merging code back and forth due to the gigantic formatting changes in the authoritative repository.

Working towards https://github.com/NOAA-EMC/spack-stack/issues/310.

For testing, see https://github.com/NOAA-EMC/spack-stack/pull/309 (**WORK IN PROGRESS**)

### CODE REVIEW

**Comment by climbfuji** [comment]
flake8 checks are now clean (https://github.com/NOAA-EMC/spack/pull/153/commits/278ba82168842207308582e523dace1a10072e6c). There is a bunch of "recommendations" on how to reformat some of the packages, but I am going to ignore those for now and make sure that the updated packages still build spack-stack in CI and on my macOS.

**Review by srherbener — APPROVED** [review]
There are so many changes we will have to rely on the CI testing to know if this PR is okay. I think that is fine since we absolutely need to do this merge to be able to stay in sync with the LLNL spack repo. I'm good with merging after we get validation from the CI testing.

**Comment by climbfuji** [comment]
> There are so many changes we will have to rely on the CI testing to know if this PR is okay. I think that is fine since we absolutely need to do this merge to be able to stay in sync with the LLNL spack repo. I'm good with merging after we get validation from the CI testing.

I agree, it's unfortunate that the spack developers decided to do a full formatting overhaul, but hopefully this is a one-off situation.

**Comment by climbfuji** [comment]
> flake8 checks are now clean ([278ba82](https://github.com/NOAA-EMC/spack/commit/278ba82168842207308582e523dace1a10072e6c)). There is a bunch of "recommendations" on how to reformat some of the packages, but I am going to ignore those for now and make sure that the updated packages still build spack-stack in CI and on my macOS.

@kgerheiser @edwardhartnett Do you think it is reasonable to do this? These packages for which `black` has formatting suggestions have always been this way, the fact that the style checker never complained about them in our fork is that it only runs checks on packages that have changed in the respective PR.

**Comment by climbfuji** [comment]
This PR is ready to merge. CI tests all pass (https://github.com/NOAA-EMC/spack-stack/pull/309 - https://github.com/NOAA-EMC/spack-stack/pull/309/commits/fc1555515d068ec74a81f60030cf589506dc13ec) and it all builds on my local macOS as well. There will be additional bug fixes required for Gaea and possibly other HPCs, but these will be fixed in follow-up PRs (e.g. https://github.com/NOAA-EMC/spack-stack/pull/301).

@kgerheiser confirmed that it is acceptable to ignore the `black` style errors for now.

**Pull request merged**
