### PR TITLE
Upstream/fork merge April 2023

### LINKED ISSUE #209: this repo needs to be synced with main spack repo
### Steps to reproduce

It does us no good to have our own version of spack. We need to expose it to the community and also let the community help us.

So we need to merge our changes to the main spack repo. We need users to be able to build from the main spack repo, and have it work the same as for us.

It's not clear that the NCO will accept updates from our fork of the main spack repo. They will accept updates on the main spack repo. That means the NCEPLIBS team will not be updating the fork of spack, we will instead be updating the main spack repo when we do a release.

THis spack fork, if it continues to be used, must fetch those changes from the main spack repo. Yet we do not seem to be updating this fork from the main spack repo  - we need to.

### Error message

v

### Information on your system

f

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
12 Apr: Changed unit tests to use Python 3.10 instead of 3.11 due to pathlib/os.stat/follow_symlinks bug. Removed codecov stuff because we don't use it and it couldn't be installed on account of being mysteriously missing from pypi/pythonhosted.

18 Apr: Various ESMF updates

Files of note (i.e., merged conflicts):

- lib/spack/spack/binary_distribution.py
- lib/spack/spack/relocate.py
- var/spack/repos/builtin/packages/bufr/package.py
- var/spack/repos/builtin/packages/crtm-fix/package.py
- var/spack/repos/builtin/packages/crtm/package.py
- var/spack/repos/builtin/packages/ecbuild/package.py
- var/spack/repos/builtin/packages/eckit/package.py
- var/spack/repos/builtin/packages/esmf/package.py
- var/spack/repos/builtin/packages/git-lfs/package.py
- var/spack/repos/builtin/packages/gsl-lite/package.py
- var/spack/repos/builtin/packages/libelf/package.py
- var/spack/repos/builtin/packages/libpng/package.py
- var/spack/repos/builtin/packages/nccmp/package.py
- var/spack/repos/builtin/packages/ncview/package.py
- var/spack/repos/builtin/packages/netcdf-c/package.py
- var/spack/repos/builtin/packages/parallelio/package.py
- var/spack/repos/builtin/packages/ufs-weather-model/package.py
- var/spack/repos/builtin/packages/upp/package.py

Closes https://github.com/NOAA-EMC/spack/issues/209

### CODE REVIEW

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA I'll mark this as ready for review

**Review by climbfuji — APPROVED** [review]
We have tested these changes fairly extensively. Let's merger this and fi any upcoming issues in our fork/branch, if needed.

**Review by ulmononian — APPROVED** [review]
i believe in your testing.

**Comment by AlexanderRichert-NOAA** [comment]
> We have tested these changes fairly extensively. Let's merger this and fi any upcoming issues in our fork/branch, if needed.

Sounds good to me. Do you usually squash-n-merge or just regular merge?

**Comment by climbfuji** [comment]
> > We have tested these changes fairly extensively. Let's merger this and fi any upcoming issues in our fork/branch, if needed.
> 
> Sounds good to me. Do you usually squash-n-merge or just regular merge?

I do regular merge to maintain the capability of cherry-picking and merging back and forth between the authoritative repo and our fork.

**Pull request merged**
