### PR TITLE
Add extra instructions for container pre-build/pre-final phases for Docker and Singularity. Add additional env variables to Ubuntu 20.04 containers.

### LINKED ISSUE #163: Need container extra instructions prior to build phase
### Summary

Some containers (e.g. Intel containers) need extra instructions before the build phase, for example adding new `apt` sources and installing the Intel oneAPI suite from there. This should be implemented for both Docker and Singularity using the existing extra-instructions logic.

### Rationale

_No response_

### Description

_No response_

### Additional information

_No response_

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Add logic for extra instructions prior to container build and final phases, as described in https://github.com/NOAA-EMC/spack/issues/163.

The PR also sanitizes `lib/jcsda-emc/spack-stack/stack/container_env.py` so that the spack style checks pass.

This PR has been tested successfully with https://github.com/NOAA-EMC/spack-stack/pull/320

The remaining failing CI test (line 1688) is because `jedi-cmake`, a dependency for `fms`, is not in the same (`builtin`) spack repo (but in `jcsda_emc`). A known issue we don't have a good solution for.

### CODE REVIEW

**Comment by climbfuji** [comment]
@mer-a-o @mark-a-potts This PR is ready to merge. It will enable building the Intel container without having to manually move instructions around. Can you please review? Thanks.

**Comment by climbfuji** [comment]
Note. Corresponding PR for the authoritative spack repository is here: https://github.com/spack/spack/pull/32478

**Review by mer-a-o — APPROVED** [review]
Changes look good to me. Thanks.

**Comment by climbfuji** [comment]
> Changes look good to me. Thanks.

Thanks!

**Pull request merged**
