### PR TITLE
mapl: add v2.46.1

### PR DESCRIPTION
**Pull request by mathomp4**
Adds MAPL 2.46.1.

My testing shows this works with mainline spack, so should work here!

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Thanks! Does this PR make our mapl package identical to the one in spack develop?

**Comment by mathomp4** [comment]
> Thanks! Does this PR make our mapl package identical to the one in spack develop?

Alllllmost. You all have:

```python
    # https://github.com/JCSDA/spack-stack/issues/769
    conflicts("+pflogger", when="@:2.40.3 %intel@2021.7:")
    conflicts("+extdata2g", when="@:2.40.3 %intel@2021.7:")
```

in your copy. I'm going to make a PR to mainline spack to get that in so that they are identical.

**Comment by climbfuji** [comment]
> > Thanks! Does this PR make our mapl package identical to the one in spack develop?
> 
> Alllllmost. You all have:
> 
> ```python
>     # https://github.com/JCSDA/spack-stack/issues/769
>     conflicts("+pflogger", when="@:2.40.3 %intel@2021.7:")
>     conflicts("+extdata2g", when="@:2.40.3 %intel@2021.7:")
> ```
> 
> in your copy. I'm going to make a PR to mainline spack to get that in so that they are identical.

Great, thanks!

**Review by climbfuji — APPROVED** [review]

**Comment by mathomp4** [comment]
Here it is: https://github.com/spack/spack/pull/44350

**Pull request merged**
